# Generated by Django 4.2.7 on 2024-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='icici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('aadhar', models.IntegerField(max_length=12)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
    ]
