# Generated by Django 4.2.7 on 2024-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('college1', models.CharField(max_length=100)),
                ('course1', models.CharField(max_length=100)),
            ],
        ),
    ]
